if (!window.has_executed) {
  window.has_executed = true;
  initializeAndAddSubtitles();
}

let executed = 0;

async function initializeAndAddSubtitles() {
  const video = await new Promise((resolve) => {
    const check = () => {
      const v = document.querySelector("video");
      v ? resolve(v) : setTimeout(check, 500);
    };
    check();
  });

  console.log(video);
  console.log(video);
  console.log(video);
  console.log(video);

  const playerData = await new Promise((resolve) => {
    const script = document.createElement("script");
    script.textContent = `document.body.setAttribute('data-player-response', 
      JSON.stringify(document.getElementsByTagName('ytd-app')[0].data.playerResponse))`;
    document.body.appendChild(script);
    script.remove();
    resolve(JSON.parse(document.body.getAttribute("data-player-response")));
    document.body.removeAttribute("data-player-response");
  });

  if (!playerData?.captions || executed) return;
  executed = 1;

  const { captionTracks, translationLanguages } = playerData.captions.playerCaptionsTracklistRenderer;

  const learningTrack = (() => {
    // First try to find auto-generated subtitles
    const autoGenerated = captionTracks.find((track) => track.vssId === "a.ru" || track.vssId === "a.uk" || track.vssId === "a.de" || track.vssId === "a.fr");
    if (autoGenerated) return autoGenerated;

    // If no auto-generated found, try manual subtitles
    return captionTracks.find((track) => track.vssId === ".ru" || track.vssId === ".uk" || track.vssId === ".de" || track.vssId === ".fr");
  })();

  if (learningTrack) {
    const englishLang = translationLanguages.find((lang) => lang.languageName.simpleText === "English");

    if (englishLang) {
      await addSubtitle(`${learningTrack.baseUrl}&fmt=vtt&tlang=${englishLang.languageCode}`, "en");
    }

    // Determine the original language from vssId and add corresponding subtitle
    const originalLang = learningTrack.vssId.replace(/[.a]/g, "");
    await addSubtitle(`${learningTrack.baseUrl}&fmt=vtt`, originalLang);
  }
}

async function addSubtitle(url, lang) {
  const video = document.querySelector("video");
  if (!video) return;

  const response = await fetch(url);
  const subtitleData = (await response.text()).replaceAll("align:start position:0%", "");

  const track = document.createElement("track");
  track.default = true;
  track.srclang = lang;
  track.src = "data:text/vtt," + encodeURIComponent(subtitleData);

  video.appendChild(track);
  track.track.mode = "showing";
}

document.addEventListener("yt-navigate-finish", () => {
  const video = document.querySelector("video");
  if (video) {
    Array.from(video.getElementsByTagName("track")).forEach((track) => {
      track.track.mode = "hidden";
      track.remove();
    });
  }
  initializeAndAddSubtitles();
});
